### ISSUE TITLE
Add (experimental) light client server functionality

### ISSUE THREAD

**Issue by benjaminion** [Consensys/teku#4230]
See [these notes](https://notes.ethereum.org/@ralexstokes/S1RSe1JlF) for some background.

> A first milestone here is to fork one of the production-grade beacon clients and build out the aforementioned functionality.

I believe that Teku's architecture makes it well suited to implementing the light client server functionality and meeting this milestone.

**Comment by jeyakatsa** [comment]
Hi @benjaminion !

I've began work on this here: https://github.com/jeyakatsa/teku/tree/lightclient/light-client

Will be updating and sending pull requests when necessary.

Available for any questions you or your team may have!

**Comment by robzajac** [comment]
Bumping with work done in #6384.
[Endpoints](https://github.com/ethereum/beacon-APIs/tree/master/apis/beacon/light_client)
[Data types](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#containers)

- [`GetLightClientBootstrap`](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/bootstrap.yaml): Returns the data for clients to startup into the light client protocol, including the current sync committee and latest block header
- [`GetLightClientUpdatesByRange`](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/updates.yaml): Returns the LightClientUpdate for the provided sync committee range, including the attested block header and the next sync committee
- [`GetLightClientFinalityUpdate`](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/finality_update.yaml): Returns the latest known LightClientFinalityUpdate
- [`GetLightClientOptimisticUpdate`](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/optimistic_update.yaml): Returns the latest known LightClientOptimisticUpdate

Will continue to track in this issue.

**Comment by robzajac** [comment]
Acceptance criteria:
- LC server endpoints are implemented, tested and deployed in teku
- Demonstrated a light client sync against a teku full node

API reference:
- [`consensus-specs`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/full-node.md)
- [`beacon-APIs`](https://github.com/ethereum/beacon-APIs/tree/master/apis/beacon/light_client)

Progress update:

General
- [x] ~Update JSON serialization according to etan's update to the light client fields https://github.com/ethereum/beacon-APIs/pull/287~
- [ ] Add support for Capella types https://github.com/ethereum/beacon-APIs/pull/293

`GetLightClientBootstrap`
- [X] ~SSZ types~
- [X] ~REST API~
- [X] ~Business logic & implementation~
- [ ] [gossip topic](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/p2p-interface.md#getlightclientbootstrap)

`GetLightClientUpdatesByRange`
- [X] ~SSZ types~
- [X] ~REST API~
- [x] ~`application/octet-stream` [custom encoding](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/updates.yaml#L37)~
- [ ] Business logic & implementation
- [ ] [gossip topic](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/p2p-interface.md#lightclientupdatesbyrange)

`GetLightClientFinalityUpdate`

Follow after `GetLightClientUpdatesByRange`
- [ ] REST API & implementation
- [ ] [gossip topic](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/p2p-interface.md#getlightclientfinalityupdate)
- [ ] [eventstream topic](https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml)

`GetLightClientOptimisticUpdate`

Follow after `GetLightClientUpdatesByRange`
- [ ] REST API & implementation
- [ ] [gossip topic](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/p2p-interface.md#getlightclientoptimisticupdate)
- [ ] [eventstream topic](https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml)

Misc
- [X] ~Implement merkle inclusion proofs for SSZ object fields~
- ~[ ] Verify merkle proofs implementation with implementation of [`calculate_merkle_root`](https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md#merkle-multiproofs)~ Not necessary, implementation is repetitive to the implementation of constructing the merkle proof itself, which can be validated by test cases.
- [X] ~`--light-client-support-enabled` flag (default true, but not all clients will elect to serve the data)~
- [ ] Cache of `LightClientUpdate` for the block retention period (~5 months)
	- Much faster than reading multiple historic `BeaconState`

I thought it would be helpful to lay this out, let me know if you have any thoughts or feedback @rolfyone @ajsutton

**Comment by lucassaldanha** [comment]
Some info: https://github.com/Consensys/teku-internal/issues/50

**Comment by akronim26** [comment]
Hey team!

I am picking up this issue to implement the server-side light client protocol implementation in Teku. I will be working on the existing scaffold and will be opening atomic pull requests as I move forward.

Open to any questions or suggestions!
