### ISSUE TITLE
[MEV boost\Builder] Builder spec `0.2.0` support

### ISSUE THREAD

**Issue by tbenr** [Consensys/teku#5396]
### Description
we want to support version `0.2.0` and . More info here:
https://github.com/ethereum/builder-specs/releases/tag/v0.2.0

https://ethereum.github.io/builder-specs/

### general flow requirements

- [x]  track builder availability status (`builder_status`)
- [x]  implement parallel calls to `builder_getHeaderV1` and `engine_getPayload` with fallback handling (error or timeout)
  - [x]  should be able to transparently handle the `builder_getPayloadV1` with the payload returned by `engine_getPayload`.
- [x]  must always use local execution engine if merge isn't completed (non-default execution payload finalized)

### Execution API Clients:
- [x] separate `builder_` api from `execution_` api clients (migrate `builder_` to `ExecutionBuilderClient`)
- [x] generic rest api client 
  - [x] implement `builder_status`
  - [x] implement `builder_registerValidatorV1`
  - [x] update `builder_getPayloadHeaderV1` to `builder_getHeaderV1`
  - [x] update `builder_proposeBlindedBlockV1` to `builder_getPayloadV1`

### ExecutionEngineChannel:
- [x] make executionengine channel more generic (rename to `ExecutionLayerChannel`).
  - Will to expose `engine_`,  `builder_` and some `eth1_` endpoints via two separate jsonrpc clients
  - analyze the the option to make the `ExecutionLayerManagerImpl` less a simple proxy for api calls and being responsible for the fallback logic. It could abstract away all the "general flow requirements".
- [x] #5610

### ExecutionEngineService:
- [x] let the service poll `builder_status` to track builder flow availability

### CLI and configuration
- [x] introduce new `eb-endpoint` (execution builder)
- [x] #5638
- [x] #5639
- [x] #5640

### Beacon Rest API:
- [x] support for validator registration (ref: https://github.com/ethereum/beacon-APIs/pull/209) in `register_validator` API. Must call `builder_registerValidator`.

### Validator Client:
- [x] #5596
- [x] #5636
- [x] #5637
- [x] #5644

### Beacon Node:
- [x] change block proposal flow to integrate `builder_` (might be easy if `ExecutionEngineChannel` will be responsible for most of the work)

### Latest Spec changes

- [x] #5595
- [x] #5613
- [x] #5873 

### Bugfix - Improvements
- [x] #5716
- [x] #5712
- [x] #5734
- [x] #5756 
- [x] #5880

### Monitoring/Logging
 - [x] #5710 
 - [x] #5711
 - [x] #5654
